In [1]:
import pandas as pd

In [3]:
df_jan = pd.read_csv("201901-citibike-tripdata.csv")

AttributeError: 'DataFrame' object has no attribute 'length'

In [5]:
df_jan.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,320,2019-01-01 00:01:47.4010,2019-01-01 00:07:07.5810,3160.0,Central Park West & W 76 St,40.778968,-73.973747,3283.0,W 89 St & Columbus Ave,40.788221,-73.970416,15839,Subscriber,1971,1
1,316,2019-01-01 00:04:43.7360,2019-01-01 00:10:00.6080,519.0,Pershing Square North,40.751873,-73.977706,518.0,E 39 St & 2 Ave,40.747804,-73.973442,32723,Subscriber,1964,1
2,591,2019-01-01 00:06:03.9970,2019-01-01 00:15:55.4380,3171.0,Amsterdam Ave & W 82 St,40.785247,-73.976673,3154.0,E 77 St & 3 Ave,40.773142,-73.958562,27451,Subscriber,1987,1
3,2719,2019-01-01 00:07:03.5450,2019-01-01 00:52:22.6500,504.0,1 Ave & E 16 St,40.732219,-73.981656,3709.0,W 15 St & 6 Ave,40.738046,-73.996430,21579,Subscriber,1990,1
4,303,2019-01-01 00:07:35.9450,2019-01-01 00:12:39.5020,229.0,Great Jones St,40.727434,-73.993790,503.0,E 20 St & Park Ave,40.738274,-73.987520,35379,Subscriber,1979,1

In [7]:
df_jan.count()

tripduration               967287
starttime                  967287
stoptime                   967287
start station id           967269
start station name         967269
start station latitude     967287
start station longitude    967287
end station id             967269
end station name           967269
end station latitude       967287
end station longitude      967287
bikeid                     967287
usertype                   967287
birth year                 967287
gender                     967287
dtype: int64

In [8]:
df_jan.dropna()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,320,2019-01-01 00:01:47.4010,2019-01-01 00:07:07.5810,3160.0,Central Park West & W 76 St,40.778968,-73.973747,3283.0,W 89 St & Columbus Ave,40.788221,-73.970416,15839,Subscriber,1971,1
1,316,2019-01-01 00:04:43.7360,2019-01-01 00:10:00.6080,519.0,Pershing Square North,40.751873,-73.977706,518.0,E 39 St & 2 Ave,40.747804,-73.973442,32723,Subscriber,1964,1
2,591,2019-01-01 00:06:03.9970,2019-01-01 00:15:55.4380,3171.0,Amsterdam Ave & W 82 St,40.785247,-73.976673,3154.0,E 77 St & 3 Ave,40.773142,-73.958562,27451,Subscriber,1987,1
3,2719,2019-01-01 00:07:03.5450,2019-01-01 00:52:22.6500,504.0,1 Ave & E 16 St,40.732219,-73.981656,3709.0,W 15 St & 6 Ave,40.738046,-73.996430,21579,Subscriber,1990,1
4,303,2019-01-01 00:07:35.9450,2019-01-01 00:12:39.5020,229.0,Great Jones St,40.727434,-73.993790,503.0,E 20 St & Park Ave,40.738274,-73.987520,35379,Subscriber,1979,1
5,535,2019-01-01 00:08:33.1790,2019-01-01 00:17:28.3540,3630.0,Frederick Douglass Blvd & W 115 St,40.803865,-73.955931,3529.0,Lenox Ave & W 130 St,40.810792,-73.943068,30315,Subscriber,1989,2
6,280,2019-01-01 00:09:21.0060,2019-01-01 00:14:01.1510,3675.0,3 Ave & E 95 St,40.784597,-73.949685,3288.0,E 88 St & 1 Ave,40.778301,-73.948813,35391,Subscriber,1987,1
7,1547,2019-01-01 00:11:22.9070,2019-01-01 00:37:10.0550,285.0,Broadway & E 14 St,40.734546,-73.990741,3358.0,Garfield Pl & 8 Ave,40.671198,-73.974841,35551,Subscriber,1981,1
8,300,2019-01-01 00:12:17.9310,2019-01-01 00:17:18.8300,3394.0,Columbia St & W 9 St,40.676999,-74.006471,3398.0,Smith St & 9 St,40.674696,-73.997858,18636,Subscriber,1990,2
9,123,2019-01-01 00:12:19.6030,2019-01-01 00:14:23.1040,432.0,E 7 St & Avenue A,40.726218,-73.983799,3656.0,E 2 St & Avenue A,40.723077,-73.985836,35206,Subscriber,1987,1
10,932,2019-01-01 00:14:02.7970,2019-01-01 00:29:35.0450,379.0,W 31 St & 7 Ave,40.749156,-73.991600,336.0,Sullivan St & Washington Sq,40.730477,-73.999061,35148,Subscriber,1986,1
11,209,2019-01-01 00:15:09.9730,2019-01-01 00:18:39.0110,438.0,St Marks Pl & 1 Ave,40.727791,-73.985649,301.0,E 2 St & Avenue B,40.722174,-73.983688,34416,Subscriber,1998,2
12,976,2019-01-01 00:15:12.8890,2019-01-01 00:31:29.1450,3452.0,Bayard St & Leonard St,40.719156,-73.948854,251.0,Mott St & Prince St,40.723180,-73.994800,35685,Subscriber,1994,1
13,97,2019-01-01 00:15:40.0140,2019-01-01 00:17:17.3120,3430.0,Richardson St & N Henry St,40.719079,-73.942237,3095.0,Graham Ave & Herbert St,40.719293,-73.945004,34307,Subscriber,1988,1
14,467,2019-01-01 00:16:22.9480,2019-01-01 00:24:10.5430,507.0,E 25 St & 2 Ave,40.739126,-73.979738,492.0,W 33 St & 7 Ave,40.750200,-73.990931,35561,Subscriber,1989,1
15,348,2019-01-01 00:17:28.9820,2019-01-01 00:23:17.6080,3095.0,Graham Ave & Herbert St,40.719293,-73.945004,3101.0,N 12 St & Bedford Ave,40.720798,-73.954847,35695,Subscriber,1988,1
16,505,2019-01-01 00:18:45.1180,2019-01-01 00:27:10.5990,3132.0,E 59 St & Madison Ave,40.763505,-73.971092,359.0,E 47 St & Park Ave,40.755103,-73.974987,31801,Subscriber,1981,1
17,3494,2019-01-01 00:18:57.5640,2019-01-01 01:17:11.5700,3171.0,Amsterdam Ave & W 82 St,40.785247,-73.976673,3164.0,Columbus Ave & W 72 St,40.777057,-73.978985,35785,Subscriber,1954,1
18,829,2019-01-01 00:19:08.1030,2019-01-01 00:32:57.3880,3165.0,Central Park West & W 72 St,40.775794,-73.976206,3295.0,Central Park W & W 96 St,40.791270,-73.964839,32106,Subscriber,1969,0
19,451,2019-01-01 00:21:00.6320,2019-01-01 00:28:31.9450,403.0,E 2 St & 2 Ave,40.725029,-73.990697,545.0,E 23 St & 1 Ave,40.736502,-73.978095,32038,Subscriber,1985,1
20,736,2019-01-01 00:21:02.9570,2019-01-01 00:33:19.4110,3165.0,Central Park West & W 72 St,40.775794,-73.976206,3295.0,Central Park W & W 96 St,40.791270,-73.964839,16761,Customer,1989,2
21,617,2019-01-01 00:21:25.8400,2019-01-01 00:31:42.9920,3159.0,W 67 St & Broadway,40.774925,-73.982666,3142.0,1 Ave & E 62 St,40.761227,-73.960940,24895,Subscriber,1998,1
22,537,2019-01-01 00:21:42.7480,2019-01-01 00:30:40.4410,3231.0,E 67 St & Park Ave,40.767801,-73.965921,519.0,Pershing Square North,40.751873,-73.977706,30089,Subscriber,1996,1
23,377,2019-01-01 00:23:26.4720,2019-01-01 00:29:43.6340,435.0,W 21 St & 6 Ave,40.741740,-73.994156,509.0,9 Ave & W 22 St,40.745497,-74.001971,32313,Subscriber,1968,2
24,643,2019-01-01 00:24:10.9070,2019-01-01 00:34:54.2950,484.0,W 44 St & 5 Ave,40.755003,-73.980144,484.0,W 44 St & 5 Ave,40.755003,-73.980144,34089,Subscriber,1975,1
25,199,2019-01-01 00:24:55.4210,2019-01-01 00:28:14.7540,3302.0,Columbus Ave & W 103 St,40.796935,-73.964341,3630.0,Frederick Douglass Blvd & W 115 St,40.803865,-73.955931,35775,Subscriber,1989,1
26,414,2019-01-01 00:24:59.4330,2019-01-01 00:31:53.8990,3321.0,Clinton St & Union St,40.683116,-73.997853,157.0,Henry St & Atlantic Ave,40.690893,-73.996123,34381,Subscriber,1975,2
27,1145,2019-01-01 00:25:00.0880,2019-01-01 00:44:05.4970,3163.0,Central Park West & W 68 St,40.773407,-73.977825,490.0,8 Ave & W 33 St,40.751551,-73.993934,24945,Customer,1969,0
28,1068,2019-01-01 00:25:13.8750,2019-01-01 00:43:01.9350,394.0,E 9 St & Avenue C,40.725213,-73.977688,3431.0,E 35 St & 3 Ave,40.746524,-73.977885,32042,Subscriber,1996,1
29,357,2019-01-01 00:25:30.3870,2019-01-01 00:31:27.5400,3170.0,W 84 St & Columbus Ave,40.785000,-73.972834,3167.0,Amsterdam Ave & W 73 St,40.779668,-73.980930,33859,Subscriber,1979,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
967257,424,2019-01-31 23:52:18.3530,2019-01-31 23:59:22.9260,3572.0,34 Ave & 38 St,40.756913,-73.921631,3617.0,28 Ave & 35 St,40.767100,-73.916986,24814,Subscriber,1990,1
967258,386,2019-01-31 23:52:23.7930,2019-01-31 23:58:50.3890,524.0,W 43 St & 6 Ave,40.755273,-73.983169,492.0,W 33 St & 7 Ave,40.750200,-73.990931,30578,Subscriber,1973,1
967259,213,2019-01-31 23:52:21.9000,2019-01-31 23:55:54.9930,3718.0,E 11 St & Avenue B,40.727464,-73.979504,301.0,E 2 St & Avenue B,40.722174,-73.983688,25435,Subscriber,1978,1
967260,774,2019-01-31 23:52:49.5920,2019-02-01 00:05:43.9180,3163.0,Central Park West & W 68 St,40.773407,-73.977825,3341.0,Central Park West & W 102 St,40.795346,-73.961860,30868,Subscriber,1984,1
967261,916,2019-01-31 23:52:54.5490,2019-02-01 00:08:11.4090,445.0,E 10 St & Avenue A,40.727408,-73.981420,265.0,Stanton St & Chrystie St,40.722293,-73.991475,35700,Subscriber,1985,1
967262,327,2019-01-31 23:53:05.5460,2019-01-31 23:58:33.0190,403.0,E 2 St & 2 Ave,40.725029,-73.990697,3435.0,Grand St & Elizabeth St,40.718822,-73.995960,34868,Subscriber,1993,1
967263,1018,2019-01-31 23:53:11.7730,2019-02-01 00:10:10.7580,513.0,W 56 St & 10 Ave,40.768254,-73.988639,498.0,Broadway & W 32 St,40.748549,-73.988084,35756,Subscriber,1941,1
967264,944,2019-01-31 23:53:14.3390,2019-02-01 00:08:58.5790,3243.0,E 58 St & 1 Ave,40.758924,-73.962262,317.0,E 6 St & Avenue B,40.724537,-73.981854,35633,Subscriber,1991,1
967265,456,2019-01-31 23:53:16.7040,2019-02-01 00:00:53.3050,3615.0,44 Dr & 21 St,40.748000,-73.946093,3560.0,28 St & 38 Ave,40.754876,-73.934326,35441,Subscriber,1980,2
967266,250,2019-01-31 23:53:19.2430,2019-01-31 23:57:30.1620,3093.0,N 6 St & Bedford Ave,40.717452,-73.958509,460.0,S 4 St & Wythe Ave,40.712859,-73.965903,33779,Subscriber,1981,1
967267,86,2019-01-31 23:54:17.4400,2019-01-31 23:55:43.9250,317.0,E 6 St & Avenue B,40.724537,-73.981854,3718.0,E 11 St & Avenue B,40.727464,-73.979504,28203,Subscriber,1969,2
967268,681,2019-01-31 23:54:18.2800,2019-02-01 00:05:39.8390,347.0,Greenwich St & W Houston St,40.728846,-74.008591,3002.0,South End Ave & Liberty St,40.711512,-74.015756,27779,Subscriber,1965,1
967269,304,2019-01-31 23:55:03.0060,2019-02-01 00:00:07.3490,3129.0,Queens Plaza North & Crescent St,40.751102,-73.940737,3121.0,Jackson Ave & 46 Rd,40.745248,-73.947333,33960,Subscriber,1996,1
967270,427,2019-01-31 23:54:55.8940,2019-02-01 00:02:03.6100,528.0,2 Ave & E 31 St,40.742909,-73.977061,466.0,W 25 St & 6 Ave,40.743954,-73.991449,34415,Subscriber,1982,1
967271,1852,2019-01-31 23:55:28.4160,2019-02-01 00:26:20.8430,438.0,St Marks Pl & 1 Ave,40.727791,-73.985649,3721.0,31 St & Newtown Ave,40.767549,-73.920933,35795,Subscriber,1989,1
967272,1513,2019-01-31 23:55:29.3520,2019-02-01 00:20:42.5530,504.0,1 Ave & E 16 St,40.732219,-73.981656,3236.0,W 42 St & Dyer Ave,40.758985,-73.993800,30597,Subscriber,1980,1
967273,293,2019-01-31 23:56:43.3000,2019-02-01 00:01:37.1380,293.0,Lafayette St & E 8 St,40.730207,-73.991026,325.0,E 19 St & 3 Ave,40.736245,-73.984738,29704,Subscriber,1971,1
967274,917,2019-01-31 23:57:28.7160,2019-02-01 00:12:45.7980,3308.0,Kane St & Clinton St,40.686176,-73.996453,3580.0,St Johns Pl & Washington Ave,40.673724,-73.963161,34327,Subscriber,1987,1
967275,291,2019-01-31 23:58:00.4710,2019-02-01 00:02:51.4890,298.0,3 Ave & Schermerhorn St,40.686832,-73.979677,416.0,Cumberland St & Lafayette Ave,40.687534,-73.972652,20505,Subscriber,1960,1
967276,404,2019-01-31 23:58:20.0050,2019-02-01 00:05:04.5000,161.0,LaGuardia Pl & W 3 St,40.729170,-73.998102,268.0,Howard St & Centre St,40.719105,-73.999733,32991,Subscriber,1998,1
967277,389,2019-01-31 23:58:43.6290,2019-02-01 00:05:13.5620,3226.0,W 82 St & Central Park West,40.782750,-73.971370,3145.0,E 84 St & Park Ave,40.778627,-73.957721,34846,Subscriber,1960,1
967278,703,2019-01-31 23:59:12.5210,2019-02-01 00:10:55.5860,470.0,W 20 St & 8 Ave,40.743453,-74.000040,127.0,Barrow St & Hudson St,40.731724,-74.006744,32666,Subscriber,1960,1
967279,245,2019-01-31 23:59:31.6600,2019-02-01 00:03:37.2060,3418.0,Plaza St West & Flatbush Ave,40.675021,-73.971115,3354.0,3 St & Prospect Park West,40.668132,-73.973638,28520,Subscriber,1984,2
967280,2535,2019-01-31 23:59:36.7480,2019-02-01 00:41:51.9970,3350.0,W 100 St & Broadway,40.797372,-73.970412,327.0,Vesey Pl & River Terrace,40.715338,-74.016584,30289,Subscriber,1951,1
967281,233,2019-01-31 16:37:28.0680,2019-01-31 16:41:21.7320,3354.0,3 St & Prospect Park West,40.668132,-73.973638,3304.0,6 Ave & 9 St,40.668127,-73.983776,32347,Subscriber,1979,1
967282,291,2019-01-31 17:33:26.4490,2019-01-31 17:38:17.8940,3354.0,3 St & Prospect Park West,40.668132,-73.973638,3423.0,West Drive & Prospect Park West,40.661063,-73.979453,19780,Subscriber,1978,2
967283,437,2019-01-31 18:57:45.3380,2019-01-31 19:05:02.4970,3354.0,3 St & Prospect Park West,40.668132,-73.973638,3313.0,6 Ave & 12 St,40.666318,-73.985462,34365,Subscriber,1976,2
967284,173,2019-01-31 19:11:41.1930,2019-01-31 19:14:34.3350,3354.0,3 St & Prospect Park West,40.668132,-73.973638,3418.0,Plaza St West & Flatbush Ave,40.675021,-73.971115,25889,Subscriber,1977,1
967285,244,2019-01-31 20:54:51.1440,2019-01-31 20:58:55.3100,3354.0,3 St & Prospect Park West,40.668132,-73.973638,3346.0,Berkeley Pl & 7 Ave,40.675147,-73.975232,34649,Subscriber,1994,1
967286,387,2019-01-31 23:38:42.1770,2019-01-31 23:45:09.4520,3354.0,3 St & Prospect Park West,40.668132,-73.973638,3549.0,Grand Ave & Bergen St,40.678045,-73.962408,17299,Subscriber,1979,1

In [9]:
df_jan.count()

tripduration               967287
starttime                  967287
stoptime                   967287
start station id           967269
start station name         967269
start station latitude     967287
start station longitude    967287
end station id             967269
end station name           967269
end station latitude       967287
end station longitude      967287
bikeid                     967287
usertype                   967287
birth year                 967287
gender                     967287
dtype: int64

In [10]:
df=pd.read_csv("JC-201901-citibike-tripdata.csv")

In [11]:
df.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,201,2019-01-01 03:09:09.7110,2019-01-01 03:12:30.8790,3183,Exchange Place,40.716247,-74.033459,3214,Essex Light Rail,40.712774,-74.036486,29612,Subscriber,1993,1
1,505,2019-01-01 05:18:00.1060,2019-01-01 05:26:25.9050,3183,Exchange Place,40.716247,-74.033459,3638,Washington St,40.724294,-74.035483,29213,Subscriber,1972,2
2,756,2019-01-01 10:36:33.3400,2019-01-01 10:49:10.2600,3183,Exchange Place,40.716247,-74.033459,3192,Liberty Light Rail,40.711242,-74.055701,26164,Subscriber,1985,1
3,1575,2019-01-01 12:43:38.6430,2019-01-01 13:09:54.5280,3183,Exchange Place,40.716247,-74.033459,3638,Washington St,40.724294,-74.035483,29672,Customer,1969,0
4,1566,2019-01-01 12:43:39.6010,2019-01-01 13:09:46.5100,3183,Exchange Place,40.716247,-74.033459,3638,Washington St,40.724294,-74.035483,29522,Customer,1969,0

In [12]:
df.count()

tripduration               19676
starttime                  19676
stoptime                   19676
start station id           19676
start station name         19676
start station latitude     19676
start station longitude    19676
end station id             19676
end station name           19676
end station latitude       19676
end station longitude      19676
bikeid                     19676
usertype                   19676
birth year                 19676
gender                     19676
dtype: int64

In [13]:
df_=pd.concat([df_jan,df])

In [14]:
df_.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,320,2019-01-01 00:01:47.4010,2019-01-01 00:07:07.5810,3160.0,Central Park West & W 76 St,40.778968,-73.973747,3283.0,W 89 St & Columbus Ave,40.788221,-73.970416,15839,Subscriber,1971,1
1,316,2019-01-01 00:04:43.7360,2019-01-01 00:10:00.6080,519.0,Pershing Square North,40.751873,-73.977706,518.0,E 39 St & 2 Ave,40.747804,-73.973442,32723,Subscriber,1964,1
2,591,2019-01-01 00:06:03.9970,2019-01-01 00:15:55.4380,3171.0,Amsterdam Ave & W 82 St,40.785247,-73.976673,3154.0,E 77 St & 3 Ave,40.773142,-73.958562,27451,Subscriber,1987,1
3,2719,2019-01-01 00:07:03.5450,2019-01-01 00:52:22.6500,504.0,1 Ave & E 16 St,40.732219,-73.981656,3709.0,W 15 St & 6 Ave,40.738046,-73.996430,21579,Subscriber,1990,1
4,303,2019-01-01 00:07:35.9450,2019-01-01 00:12:39.5020,229.0,Great Jones St,40.727434,-73.993790,503.0,E 20 St & Park Ave,40.738274,-73.987520,35379,Subscriber,1979,1

In [15]:
df_.count()

tripduration               986963
starttime                  986963
stoptime                   986963
start station id           986945
start station name         986945
start station latitude     986963
start station longitude    986963
end station id             986945
end station name           986945
end station latitude       986963
end station longitude      986963
bikeid                     986963
usertype                   986963
birth year                 986963
gender                     986963
dtype: int64

In [19]:
df_.keys()

Index(['tripduration', 'starttime', 'stoptime', 'start station id',
       'start station name', 'start station latitude',
       'start station longitude', 'end station id', 'end station name',
       'end station latitude', 'end station longitude', 'bikeid', 'usertype',
       'birth year', 'gender', 'age'],
      dtype='object')

In [17]:
df_["age"]=2019 - df_["birth year"]

In [18]:
df_["age"]

0        48
1        55
2        32
3        29
4        40
5        30
6        32
7        38
8        29
9        32
10       33
11       21
12       25
13       31
14       30
15       31
16       38
17       65
18       50
19       34
20       30
21       21
22       23
23       51
24       44
25       30
26       44
27       50
28       23
29       40
         ..
19646    28
19647    42
19648    28
19649    31
19650    28
19651    24
19652    36
19653    28
19654    28
19655    28
19656    31
19657    28
19658    21
19659    42
19660    36
19661    42
19662    42
19663    28
19664    28
19665    42
19666    28
19667    42
19668    36
19669    28
19670    42
19671    42
19672    42
19673    21
19674    42
19675    42
Name: age, Length: 986963, dtype: int64

In [38]:
df_gender=[]
for i in df_["gender"]:
    if i ==0:
#         print(0)
        df_gender.append("unknown")
    elif i==1:
#         print(1)
        df_gender.append("male")
    else: 
#         print(2)
        df_gender.append("female")

df_gender

df_["gendertext"]=df_gender

In [39]:
df_.count()

tripduration               986963
starttime                  986963
stoptime                   986963
start station id           986945
start station name         986945
start station latitude     986963
start station longitude    986963
end station id             986945
end station name           986945
end station latitude       986963
end station longitude      986963
bikeid                     986963
usertype                   986963
birth year                 986963
gender                     986963
age                        986963
gendertext                 986963
dtype: int64

In [40]:
df_=df_[['tripduration', 'starttime', 'stoptime', 'start station id',
       'start station name', 'start station latitude',
       'start station longitude', 'end station id', 'end station name',
       'end station latitude', 'end station longitude', 'bikeid', 'usertype',
        'gender', 'age']]

In [41]:
df_.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,gender,age
0,320,2019-01-01 00:01:47.4010,2019-01-01 00:07:07.5810,3160.0,Central Park West & W 76 St,40.778968,-73.973747,3283.0,W 89 St & Columbus Ave,40.788221,-73.970416,15839,Subscriber,1,48
1,316,2019-01-01 00:04:43.7360,2019-01-01 00:10:00.6080,519.0,Pershing Square North,40.751873,-73.977706,518.0,E 39 St & 2 Ave,40.747804,-73.973442,32723,Subscriber,1,55
2,591,2019-01-01 00:06:03.9970,2019-01-01 00:15:55.4380,3171.0,Amsterdam Ave & W 82 St,40.785247,-73.976673,3154.0,E 77 St & 3 Ave,40.773142,-73.958562,27451,Subscriber,1,32
3,2719,2019-01-01 00:07:03.5450,2019-01-01 00:52:22.6500,504.0,1 Ave & E 16 St,40.732219,-73.981656,3709.0,W 15 St & 6 Ave,40.738046,-73.996430,21579,Subscriber,1,29
4,303,2019-01-01 00:07:35.9450,2019-01-01 00:12:39.5020,229.0,Great Jones St,40.727434,-73.993790,503.0,E 20 St & Park Ave,40.738274,-73.987520,35379,Subscriber,1,40

In [42]:
df_.to_csv("201901-citibike-cleandata.csv")

In [43]:
df_feb = pd.read_csv("201902-citibike-tripdata.csv")

df_feb.dropna()



df=pd.read_csv("JC-201902-citibike-tripdata.csv")



df_=pd.concat([df_feb,df])

df_.head()

df_.keys()

df_["age"]=2019 - df_["birth year"]





df_=df_[['tripduration', 'starttime', 'stoptime', 'start station id',
       'start station name', 'start station latitude',
       'start station longitude', 'end station id', 'end station name',
       'end station latitude', 'end station longitude', 'bikeid', 'usertype',
        'gender', 'age']]



df_.to_csv("201902-citibike-cleandata.csv")

In [44]:
df_mar = pd.read_csv("201903-citibike-tripdata.csv")

df_mar.dropna()



df=pd.read_csv("JC-201903-citibike-tripdata.csv")



df_=pd.concat([df_mar,df])

df_.head()

df_.keys()

df_["age"]=2019 - df_["birth year"]





df_=df_[['tripduration', 'starttime', 'stoptime', 'start station id',
       'start station name', 'start station latitude',
       'start station longitude', 'end station id', 'end station name',
       'end station latitude', 'end station longitude', 'bikeid', 'usertype',
        'gender', 'age']]



df_.to_csv("201903-citibike-cleandata.csv")

In [45]:
df_apr = pd.read_csv("201904-citibike-tripdata.csv")

df_apr.dropna()



df=pd.read_csv("JC-201904-citibike-tripdata.csv")



df_=pd.concat([df_apr,df])

df_.head()

df_.keys()

df_["age"]=2019 - df_["birth year"]





df_=df_[['tripduration', 'starttime', 'stoptime', 'start station id',
       'start station name', 'start station latitude',
       'start station longitude', 'end station id', 'end station name',
       'end station latitude', 'end station longitude', 'bikeid', 'usertype',
        'gender', 'age']]



df_.to_csv("201904-citibike-cleandata.csv")

In [46]:
df_may = pd.read_csv("201905-citibike-tripdata.csv")

df_may.dropna()



df=pd.read_csv("JC-201905-citibike-tripdata.csv")



df_=pd.concat([df_may,df])

df_.head()

df_.keys()

df_["age"]=2019 - df_["birth year"]





df_=df_[['tripduration', 'starttime', 'stoptime', 'start station id',
       'start station name', 'start station latitude',
       'start station longitude', 'end station id', 'end station name',
       'end station latitude', 'end station longitude', 'bikeid', 'usertype',
        'gender', 'age']]



df_.to_csv("201905-citibike-cleandata.csv")